- name: variables
  hosts: web
  vars:
      COURSE: "Devops with aws"
      DURATION: "120 HRS"
      TRAINER: "Gopi"
  tasks:
  - name: print the information
    ansible.builtin.debug:
     msg: " Hi i am learning {{COURSE}} , duration is {{DURATION}} , Trainer is {{TRAINER}}"