- name: variables
  hosts: web
  # vars:
  #     COURSE: "Devops with aws" #play level variables
  #     DURATION: "120 HRS"
  #     TRAINER: "Gopi"
  # vars_files:
  # -  05-vars-file.yaml
  # vars_prompt:
  # - name: COURSE
  #   prompt: please enter the course name
  # - name: TRAINER
  #   prompt: please enter trainer name 
  # - name: DURATION
  #   prompt: please enter duration
  #   private: false
  tasks:
  - name: print the information
    ansible.builtin.debug:
     msg: " Hi i am learning {{COURSE}} , duration is {{DURATION}} , Trainer is {{TRAINER}}"

  # - name : print the information again
  #   vars:
  #       COURSE: "ansible"    #task level variable
  #   ansible.builtin.debug:
  #    msg: " Hi i am learning {{COURSE}} , duration is {{DURATION}} , Trainer is {{TRAINER}}"