- name: create a user
  hosts: web
  vars:
      USERNAME: expense #play level varible
  # vars_prompt:          # varable given at rumtime by the user
  # - name: USERNAME
  #   prompt: please enter the username   
  #   private: false
  # vars_files:           # Variables passing through a file
  # - 05-vars-file.yaml
  tasks:
  - name: check expense user
    ansible.builtin.command: id {{USERNAME}}
    register: USER 
    ignore_errors: true    # here output of above command stored in USER variable
    

  - name: check user info
    ansible.builtin.debug:
     msg: "{{USER}}"
     
  - name: create expense user
    ansible.builtin.command: useradd {{USERNAME}}
    when: USER.rc !=0

