- name: creating instances and route 53 records
  hosts: local
  connection: local
  vars:
     sg_group: "sg-0f2ec98b878c6d63f"
     subnet_id: "subnet-038f7624321ae7a46"
     ami_id: "ami-09c813fb71547fc4f"
     instances:
     - mysql
     - backend
     - frontend
  tasks:

  - name: installing boto3 and botocore 
    ansible.builtin.pip:
      name:
      - boto3
      - botocore
      state: present
      executable: pip3.9
      
  - name: creating 3 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t2.micro"
      security_group: "{{ sg_group }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances