- name: filter/function examples
  hosts: web
  vars:
    my_ip: "172.31.81.1"
  tasks:
  - name: check ip address valid or not
    ansible.builtin.debug:
      msg: "{{ my_ip | ansible.utils.ipv4 }}"
    