- name: filter/function examples
  hosts: web
  tasks:
  - name: course info
    ansible.builtin.debug:
     msg: " course is {{ course | default ('devops')}}"

  - name: convert dictionary to list/items
    vars:
      tools:
        ci: jenkins
        cm: ansible
        infra: terraform
        cloud: aws
    ansible.builtin.debug:
      msg: " {{ tools | dict2items }}"
