- name: check the given number is greater than 100 or not
  hosts: web
  vars_prompt:
  - name: number
    prompt: please enter the given number
    private: false
  tasks:
  - name: check {{ number }} is greater than 100 or not
    ansible.builtin.debug:
      msg: " the {{ number }} is greater than 100"
    when: number | int  > 100
  
    
