- name: filter/function examples
  hosts: web
  vars:
    my_ip: "155.31.81.255"
  tasks:
  - name: check ip address valid or not
    ansible.builtin.debug:
      msg: "{{ my_ip | ansible.utils.ipv4 }}"
    