- name: create user
  hosts: web
  tasks: 
  - name: create expense user
    ansible.builtin.command: id expense
    register: user_info

  - name: print the user info
    ansible.builtin.debug:
      msg: "user info is {{ user_info }}"