- name: check the given number is greater than 100 or not
  hosts: web
  vars: 
    number: 1
  tasks:
  - name: check {{ number }} is greater than 100 or not
    ansible.builtin.debug:
      msg: " the {{ number }} is greater than 100"
    when: number > 100
  
    
