- name: filter/function examples
  hosts: web
  tasks:
  - name: {{ number }} is greater than 100 or not
    ansible.builtin.debug:
     msg: " {{ number | default ('120')} is greater than 100}"
     when: number | int > 100