- name: using variables to print the message
  hosts: web
  # vars:
  #    course: "devops with aws"
  #    duration: 120hrs
  tasks:
  - name: print the info
    ansible.builtin.debug:
      msg: " hi i am learing {{ course }}, duration is {{ duration }}"

  
    
