- name: install the nginx and run
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start and enable the nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes


    
