- name: check the given number is greater than 100 or not
  hosts: web
  # vars_prompt:
  # - name: number
  #   prompt: please enter the given number
  #   private: false
  tasks:
  - name: check given is greater than 100 or not
    ansible.builtin.debug:
      msg: " the {{ number | default 121 }} is greater than 100"
    when: number | int  > 100
  
    
