- name: using variables to print the course info
  hosts: web
  vars:
     course: "devops with aws-vars"
     duration: 120hrs
     topics:
     - linux commands
     - shell script
     - ansible
     - terraform
     - aws
     - k8
     tools:
       ci: jenkins
       cm: ansible
       cloud: aws
       aws:
       - iam
       - s3
       - vpc
     live: true

  tasks:
  - name: print the info
    ansible.builtin.debug:
      msg: " hi i am learing {{ course }}, duration is {{ duration }} , topics are {{ topics }} , tools are {{ tools }}, live is {{ live }}"

  
    
